"use client";
import {useState,useEffect} from "react";
import {ArrowDown,ArrowUpRight,Play,Pause,Volume2,Users,Crown,Shield,Sparkles,Send,Lightbulb,Heart} from "lucide-react";
const owners=[{name:"Jonathan",username:"@pejuck",image:"/members/owner.jpg",link:"https://t.me/pejuck"}];
const admins=[{name:"Kafka",username:"@sNSFW",image:"/members/admin-1.jpg",link:"https://t.me/sNSFW"},{name:"Naeera",username:"@nnaeerae",image:"/members/admin-2.jpg",link:"https://t.me/nnaeerae"}];
const adminSoonSlots=2;
const members=[
{name:"Aaron",username:"@iPelacak",image:"/members/member-1.jpg",link:"https://t.me/iPelacak"},
{name:"Yzekiel",username:"@Yzklie",image:"/members/member-2.jpg",link:"https://t.me/Yzklie"},
{name:"Voucaz",username:"@dGroan",image:"/members/member-3.jpg",link:"https://t.me/dGroan"},
{name:"Isagi",username:"@mcatlantics",image:"/members/member-4.jpg",link:"https://t.me/mcatlantics"},
{name:"Python",username:"@pythfvck",image:"/members/member-5.jpg",link:"https://t.me/pythfvck"},
{name:"Renjaka",username:"@politikg",image:"/members/member-6.svg",link:"https://t.me/politikg"},
{name:"Hasbian",username:"@hazbiyan",image:"/members/member-7.jpg",link:"https://t.me/hazbiyan"},
{name:"Jude",username:"@telanjhang",image:"/members/member-8.svg",link:"https://t.me/telanjhang"},
{name:"Marmeiio",username:"@Zoobiecmo",image:"/members/member-9.jpg",link:"https://t.me/Zoobiecmo"},
{name:"Cleyla",username:"@aldhokeanolan",image:"/members/member-2.svg",link:"https://t.me/aldhokeanolan"},
{name:"Aysh",username:"@jameszhouyu",image:"/members/member-11.jpg",link:"https://t.me/jameszhouyu"},
{name:"Jane",username:"@iPJ4nne",image:"/members/member-12.jpg",link:"https://t.me/iPJ4nne"},
{name:"Juan",username:"@juansvn",image:"/members/member-13.jpg",link:"https://t.me/juansvn"},
{name:"Leisha",username:"@leishaam",image:"/members/member-1.svg",link:"https://t.me/leishaam"},
{name:"Malv",username:"@saintpoule",image:"/members/member-15.jpg",link:"https://t.me/saintpoule"},
{name:"Mbiey",username:"@boesyhiL",image:"/members/member-16.jpg",link:"https://t.me/boesyhiL"},
{name:"Sergio",username:"@m4ndeiz",image:"/members/member-17.jpg",link:"https://t.me/m4ndeiz"},
{name:"Harua Hirara",username:"@rramengmbul",image:"/members/member-18.jpg",link:"https://t.me/rramengmbul"},
{name:"Jean",username:"-",image:"/members/member-19.jpg",link:"https://t.me/username"},
{name:"Poje",username:"@crossdline3",image:"/members/member-20.jpg",link:"https://t.me/crossdline3"},
];
const videos=[1,2,3].map(i=>({id:`00${i}`,src:`/videos/goofies-${i}.mp4`,poster:`/videos/poster-${i}.svg`,caption:`GOOFIES CLIP #${i}`}));
function PersonCard({person,type}){return <a className={`polaroid ${type.toLowerCase()}`} href={person.link} target="_blank" rel="noreferrer"><div className="polaroid-photo"><img src={person.image} alt={person.name}/>{type!=="MEMBER"&&<span className="mini-badge">{type}</span>}</div><div className="polaroid-caption"><div className="polaroid-text"><strong>{person.name}</strong><span>{person.username}</span></div><ArrowUpRight className="person-arrow" size={18}/></div></a>}
function SoonCard({label}){return <div className="polaroid soon"><div className="polaroid-photo"><span className="soon-mark">?</span></div><div className="polaroid-caption"><div className="polaroid-text"><strong>{label}</strong><span>coming soon</span></div></div></div>}
function SectionTitle({eyebrow,title,text}){return <div className="section-title reveal"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function timeAgo(t){const s=Math.floor((Date.now()-t)/1000);if(s<60)return"baru aja";const m=Math.floor(s/60);if(m<60)return`${m} menit lalu`;const h=Math.floor(m/60);if(h<24)return`${h} jam lalu`;return`${Math.floor(h/24)} hari lalu`}
const MAX=300;
function Confess(){
const[items,setItems]=useState([]);const[loaded,setLoaded]=useState(false);const[type,setType]=useState("confession");const[text,setText]=useState("");const[trap,setTrap]=useState("");const[status,setStatus]=useState({kind:"",msg:""});const[sending,setSending]=useState(false);const[all,setAll]=useState(false);
useEffect(()=>{fetch("/api/messages",{cache:"no-store"}).then(r=>r.json()).then(j=>setItems(j.messages||[])).catch(()=>{}).finally(()=>setLoaded(true))},[]);
const submit=async e=>{e.preventDefault();if(sending)return;const t=text.trim();if(t.length<5){setStatus({kind:"err",msg:"Tulis dikit lah, minimal 5 karakter."});return}setSending(true);setStatus({kind:"",msg:""});try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,text:t,website:trap})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal ngirim.");if(j.message)setItems(p=>[j.message,...p]);setText("");setStatus({kind:"ok",msg:"Sent. Aman, nama lo nggak ikut masuk."})}catch(err){setStatus({kind:"err",msg:err.message})}setSending(false)};
const shown=all?items:items.slice(0,9);
return <section id="confess" className="confess-section"><SectionTitle eyebrow="04 — THE BOX" title="got something to say?" text="Mau confession, mau ngasih saran, atau cuma pengen ngomong sesuatu? Drop aja di sini. No name, no pressure."/><div className="confess-layout"><form className="confess-form reveal" onSubmit={submit}><div className="type-pills"><button type="button" className={type==="confession"?"active":""} onClick={()=>setType("confession")}><Heart size={14}/>confession</button><button type="button" className={type==="saran"?"active":""} onClick={()=>setType("saran")}><Lightbulb size={14}/>saran</button></div><textarea value={text} maxLength={MAX} onChange={e=>setText(e.target.value)} placeholder={type==="confession"?"just say whatever's on your mind...":"got an idea? drop it here."}/><input className="hp" tabIndex={-1} autoComplete="off" aria-hidden="true" name="website" value={trap} onChange={e=>setTrap(e.target.value)}/><div className="form-foot"><span className="char-count">{text.length}/{MAX}</span><button type="submit" className="send-button" disabled={sending}>{sending?"sending...":"send it"}<Send size={15}/></button></div>{status.msg&&<p className={`form-status ${status.kind}`}>{status.msg}</p>}</form><div className="notes-wrap">{loaded&&items.length===0&&<p className="notes-empty">Belum ada apa-apa di sini. Be the first.</p>}<div className="notes">{shown.map((m,i)=><article key={m.id} className={`note ${m.type}`} style={{"--tilt":`${i%2?1.2:-1.2}deg`}}><span className="note-tag">{m.type==="saran"?"SARAN":"CONFESSION"}</span><p>{m.text}</p><div className="note-foot"><span>— Anonim</span><span>{timeAgo(m.createdAt)}</span></div></article>)}</div>{items.length>9&&<button className="more-button notes-more" onClick={()=>setAll(!all)}>{all?"show less":`lihat semua (${items.length})`}</button>}</div></div></section>}
export default function Home(){const[playing,setPlaying]=useState(false);const[showMore,setShowMore]=useState(false);useEffect(()=>{const els=document.querySelectorAll(".reveal");const io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle("in",e.isIntersecting)),{threshold:.12});els.forEach(el=>io.observe(el));return()=>io.disconnect()},[]);const toggleMusic=()=>{const a=document.getElementById("bg-music");if(!a)return;if(playing){a.pause();setPlaying(false)}else{a.play().then(()=>setPlaying(true)).catch(()=>alert("Browser ngeblok autoplay. Klik tombol musiknya lagi setelah berinteraksi dengan halaman."))}};const displayed=showMore?members:members.slice(0,4);return <main><audio id="bg-music" src="/music.mp3" loop/><button className="music-button" onClick={toggleMusic}>{playing?<Pause size={17}/>:<Play size={17}/>}<span>{playing?"playing":"music"}</span><Volume2 size={15}/></button><nav className="navbar"><a href="#home" className="brand">GOOFIES<span>®</span></a><div className="nav-links"><a href="#people">people</a><a href="#chaos">vibe</a><a href="#video">archive</a><a href="#confess">spill</a></div></nav>
<section id="home" className="hero"><div className="hero-grid"/><div className="hero-noise"/><div className="hero-content"><div className="status-pill"><span className="status-dot"/>currently: being unserious</div><p className="hero-kicker">A VERY SERIOUS CIRCLE OF VERY unserious PEOPLE</p><h1>WE ARE<br/><span>GOOFIES.</span></h1><p className="hero-copy">just a bunch of people<br/>who somehow became friends.</p><a href="#people" className="hero-button">meet the chaos <ArrowDown size={17}/></a></div><div className="hero-sticker sticker-one">ZERO THOUGHTS</div><div className="hero-sticker sticker-two">JUST VIBES</div><div className="hero-bottom"><span>keep scrolling</span><span>01 / 04</span></div></section>
<section id="people" className="people-section"><SectionTitle eyebrow="01 — THE PEOPLE" title="so, who's here?" text="Meet the people behind all the noise, questionable decisions, and somehow-functional friendship."/><div className="role-block reveal"><div className="role-heading center"><Crown size={18}/><span>OWNER</span></div><div className="card-row">{owners.map(p=><PersonCard key={p.username} person={p} type="OWNER"/>)}</div></div><div className="role-block"><div className="role-heading center"><Shield size={18}/><span>ADMIN</span></div><div className="card-row">{admins.map(p=><PersonCard key={p.username} person={p} type="ADMIN"/>)}{Array.from({length:adminSoonSlots}).map((_,i)=><SoonCard key={i} label="someone soon"/>)}</div></div><div className="member-heading reveal"><div><span className="eyebrow">EVERYONE ELSE</span><h3>MEMBERS</h3></div><div className="member-count"><Users size={17}/>{members.length} goofies</div></div><div className="marquee-window reveal"><div className="marquee-track" style={{animationDuration:`${Math.max(60,members.length*18)}s`}}>{[...members,...members].map((p,i)=><PersonCard key={p.username+i} person={p} type="MEMBER"/>)}</div></div><div className="mobile-members reveal">{displayed.map(p=><PersonCard key={p.username} person={p} type="MEMBER"/>)}{members.length>4&&<button className="more-button" onClick={()=>setShowMore(!showMore)}>{showMore?"show less":"show all members"}</button>}</div></section>
<section id="chaos" className="chaos-section"><div className="chaos-copy reveal"><span className="eyebrow">02 — THE VIBE</span><h2>Too much.<br/><em>Too online.</em><br/>Still here.</h2><p>Nobody really knows how this started. We just kept talking, kept laughing, and somehow ended up with a whole circle.</p></div><div className="reveal"><div className="chaos-card"><div className="chaos-card-top"><Sparkles size={20}/><span>GOOFIES™</span></div><div className="chaos-big">:3</div><div className="chaos-card-bottom"><span>professionally unserious</span><span>∞</span></div></div></div></section>
<section id="video" className="video-section"><SectionTitle eyebrow="03 — THE ARCHIVE" title="proof we're real." text="A few moments that probably should've stayed in someone's camera roll. Unfortunately, they're here now."/><div className="video-grid">{videos.map((v,i)=><div className="video-card reveal" style={{"--d":`${i*140}ms`}} key={v.id}><div className="video-phone"><video controls playsInline preload="metadata" poster={v.poster}><source src={v.src} type="video/mp4"/>Browser kamu tidak mendukung video.</video><div className="video-label">ARCHIVE / {v.id}</div></div><p className="video-caption">{v.caption}</p></div>)}</div></section>
<Confess/>
<footer><div className="footer-brand">GOOFIES<span>®</span></div><p>gupis kembang kempis</p><span className="footer-year">2026</span></footer></main>}